version: "3"

services:
  jekyll-ludichou-container:
    image: my-ruby-env:latest # This is image built from Dockerfile
    container_name: local_jekyll
    restart: always
    tty: true
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 4000"
    stdin_open: true